name: Deploy DevTest Lab

on:
  push:
    branches:
      - main

jobs:
  deploy:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout code
        uses: actions/checkout@v2

      - name: Install Bicep CLI
        run: |
          sudo apt-get update
          sudo apt-get install -y bicep

      - name: Build Bicep file
        run: bicep build devtestlab.bicep

      - name: Deploy resources
        uses: azure/login@v1
        with:
          creds: ${{ secrets.AZURE_CREDENTIALS }}

      - name: Create DevTest Lab
        run: az deployment sub create --name DevTestLabDeployment --location westus --template-file CreateRG.bicep --parameters labName=myDevTestLab labLocation=westus
