on:
  push:
    branches:
      - main

jobs:
  deploy:
    runs-on: ubuntu-latest

    env:
      AZURE_RESOURCEGROUP_NAME: newtest1234
      LOCATION: eastus
      ENVIRONMENT: nonprod

    steps:
      - name: Checkout Repository
        uses: actions/checkout@v2

      - name: Set up Azure CLI
        uses: azure/login@v1
        with:
          creds: ${{ secrets.AZURE_CREDENTIALS }}

      - name: Create Resource Group and Deploy Resources
        run: |
           # az group create --name $AZURE_RESOURCEGROUP_NAME --location $LOCATION
           # az deployment group create --resource-group $AZURE_RESOURCEGROUP_NAME --template-file './actions/bicep/storage.bicep'
           az deployment group create --resource-group TestSandbox --template-file './actions/bicep/CreateRG.bicep' --parameters labName=AzureLabs vmName=AzureVMsTest userName=pjagan


       
     
