name: Create Azure Resource Group

on:
  push:
    branches:
      - main
      
jobs:
  connect-to-azure:
    runs-on: ubuntu-latest
    steps:
      - uses: Azure/login@v1
        with:
          client-id: ${{ secrets.AZURE_SP_CLIENT_ID }}
          client-secret: ${{ secrets.AZURE_SP_CLIENT_SECRET }}
          tenant-id: ${{ secrets.AZURE_SP_TENANT_ID }}
          subscription-id: ${{ secrets.AZURE_SP_SUBSCRIPTION_ID }}
      - name: Run Azure commands using the authenticated identity
        run: |
          az resource list
