on: 
      workflow_dispatch:
 
name: AzureLoginSample
jobs:
 
  build-and-deploy:
    runs-on: ubuntu-latest
    steps:
      - name: Azure login
        uses: azure/login@v1
      
        with:
          creds: ${{ secrets.AZURE_CREDENTIALS }}
          auth-type: SERVICE_PRINCIPAL
      - name: Create Resource Group
        run: az group create --name TestSandbox --location eastus
        
      - name: Deploy Bicep template
        run: az deployment sub create -l eastus -f CreateRG.bicep

